# .github/workflows/runOnGitHub.yml
# GitHub Actions documentation
# => https://docs.github.com/en/actions
name: runOnGitHub

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
jobs:
  gradle:
    strategy:
      matrix:
        #os:  [ubuntu-latest, macos-latest, windows-latest]
        os:  [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: install dependencies ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt install libcurl4-openssl-dev

      # Execute Gradle commands in GitHub Actions workflows
      # => https://github.com/marketplace/actions/gradle-command
      - id: gradle
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: runOnGitHub
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
      - id: artifact
        name: Add build scan to the artifact
        uses: actions/upload-artifact@v2
        with:
          name: buildscan-assemble
          path: 'buildscan.log'
